### ISSUE TITLE
Fails for PTK cubes

### ISSUE THREAD

**Issue by plinders** [tercen/read_pgcube_operator#1]
Tercen reports the following error after importing a cube of PTK data with dimensions 3969 columns, 197 rows (728112 cells total) from BioNavigator. (Cube dump export v2 from BioNavigator fails for larger cubes than 4000 columns)

Edit: also failed for a cube with dimensions 1584columns, 197 rows (312048cells total). After further testing of the workflow it works fine for STK data (barcodes starting with 71). Importing of .RData Cube Dump of "old" PTK data (as seen in demo from Faris barcodes starting with 63, 144 peptides) works as expected. "New" PTK data (barcodes starting with 64, 196 peptides) consistently fails and give the error below. This happens for all sizes of cubes, whether it's only 1 barcode or many barcodes.

Thank you for fixing this issue,

Best,

Peter, Dirk and Savi

![image](https://user-images.githubusercontent.com/10002620/133774105-a55bcf18-51b7-4b27-b475-400532fcbde2.png)

**Comment by rdewijn** [comment]
@fnaji: this has probably something to do with special (non UTF-8) characters in the input file.  Can you fix this?
@plinders: can you add an offensive file for use in debugginG?

**Comment by plinders** [comment]
Here's an example CubeDump that fails

[PTK_test_dataCubeDump.zip](https://github.com/tercen/read_pgcube_operator/files/7195400/PTK_test_dataCubeDump.zip)

**Comment by ginberg** [comment]
this is fixed in latest version (0.0.4). See [this workflow](https://tercen.com/pamgene/w/d877ec095044016afb82595652ad990e)
